# Generated by Django 4.0.1 on 2022-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_code', models.CharField(max_length=10)),
                ('pair_price', models.DecimalField(decimal_places=8, max_digits=24)),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'quote',
            },
        ),
    ]
